---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: 6.6.6
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: "filesystem"
      storage_config:
        filesystem:
          directory: /var/loki/
        tsdb_shipper:
          active_index_directory: /var/loki/tsdb-index
          cache_location: /var/loki/tsdb-cache
      compactor:
        working_directory: /var/loki/compactor
        retention_enabled: true
        retention_delete_delay: 2h
        delete_request_cancel_period: 72h
        delete_request_store: filesystem
      limits_config:
        retention_period: 72h
        deletion_mode: filter-and-delete
      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
    singleBinary:
      replicas: 1
    read:
      replicas: 0
    backend:
      replicas: 0
    write:
      replicas: 0
    monitoring:
      dashboards:
        enabled: true
      selfMonitoring:
        enabled: true
        grafanaAgent:
          installOperator: false
